/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package progra1.GUI;

import java.util.ArrayList;
import javax.swing.JFileChooser;
import static org.apache.poi.hssf.usermodel.HeaderFooter.file;
import progra1.logica.Disco;
import progra1.logica.RadioEmisora;
import java.io.File;
import javax.swing.JOptionPane;

/**
 *
 * @author Mau
 */
public class AgregarCancion extends javax.swing.JFrame {
    
    private static Disco disc;

    /**
     * Creates new form AgregarCancion
     */
    public AgregarCancion() {

        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        tbNombreC = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        tbDuracionC = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        tbCantanteC = new javax.swing.JTextField();
        tbGeneroC = new javax.swing.JTextField();
        btAgregarC = new javax.swing.JButton();
        btExcel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btCerrar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setText("Agregar canción");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 35, -1, -1));

        tbNombreC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbNombreCActionPerformed(evt);
            }
        });
        getContentPane().add(tbNombreC, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 78, 110, -1));

        jLabel18.setText("Duración");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));
        getContentPane().add(tbDuracionC, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 116, 110, -1));

        jLabel16.setText("Nombre");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        jLabel15.setText("Cantante");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 157, -1, -1));

        jLabel22.setText("Género");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 195, -1, -1));
        getContentPane().add(tbCantanteC, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 154, 110, -1));

        tbGeneroC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbGeneroCActionPerformed(evt);
            }
        });
        getContentPane().add(tbGeneroC, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 192, 110, -1));

        btAgregarC.setText("Agregar");
        btAgregarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgregarCActionPerformed(evt);
            }
        });
        getContentPane().add(btAgregarC, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, -1, -1));

        btExcel.setText("Importar desde Excel");
        btExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcelActionPerformed(evt);
            }
        });
        getContentPane().add(btExcel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 276, -1, -1));

        btCerrar.setText("Finalizar");
        btCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, -1, -1));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbNombreCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbNombreCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbNombreCActionPerformed

    private void btExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcelActionPerformed

            JFileChooser f = new JFileChooser();
            f.showOpenDialog(f);
            String p= f.getSelectedFile().getAbsolutePath();
   

            
            try{
              AgregarCancion.disc.Cargarlista_Canciones(p,disc.getNombre());
              JOptionPane.showMessageDialog(null, "Importación hecha"); 
              
            }
            
            catch(Exception e){
                JOptionPane.showMessageDialog(null, "No se puedo cargar archivo"); 
                
            }
            
    }//GEN-LAST:event_btExcelActionPerformed

    private void tbGeneroCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbGeneroCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbGeneroCActionPerformed

    private void btAgregarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgregarCActionPerformed
        String nombre =  tbNombreC.getText();
        String duracion = tbDuracionC.getText();
        String cantante = tbCantanteC.getText();
        String genero = tbGeneroC.getText();
        String dis = disc.getNombre();
        
      
        if  (nombre.isEmpty() || duracion.isEmpty() || cantante.isEmpty() || genero.isEmpty() ){
            JOptionPane.showMessageDialog(null, "Debe rellenar todos los espacios"); 
            
        } else {
            
            try{
                float durac = Float.parseFloat(duracion);
                
                
                AgregarCancion.disc.Agregar_C(nombre, durac, cantante, genero, dis);
 
                JOptionPane.showMessageDialog(null, "Canción agregada");
                /*tbNombreC
                tbDuracionC.getText();
                tbCantanteC.getText();
                tbGeneroC.getText();*/
                
                
                
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Duración debe ser un número");
            }
             
             
            
            
            
            
        }
        
    }//GEN-LAST:event_btAgregarCActionPerformed

    private void btCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCerrarActionPerformed
                RadioEmisora r1 = Principal.getEmisora();
                r1.Agregar_D(disc);
                Principal.setEmisora(r1);
                this.dispose();
    }//GEN-LAST:event_btCerrarActionPerformed

    /**
     * @param disco

     * @param args the command line arguments
     */
    public void iniciar(Disco disco){
           AgregarCancion.disc=disco;
      
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarCancion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarCancion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarCancion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarCancion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarCancion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAgregarC;
    private javax.swing.JButton btCerrar;
    private javax.swing.JButton btExcel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField tbCantanteC;
    private javax.swing.JTextField tbDuracionC;
    private javax.swing.JTextField tbGeneroC;
    private javax.swing.JTextField tbNombreC;
    // End of variables declaration//GEN-END:variables
}
