/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package progra1.GUI;

import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import progra1.logica.Disco;
import progra1.logica.RadioEmisora;
import progra1.logica.Cancion;

/**
 *
 * @author Mau
 */
public class AgregarDisco extends javax.swing.JFrame {

    /**
     * Creates new form AgregarDisco
     */
    JFileChooser f = new JFileChooser();
    JFileChooser f2 = new JFileChooser(); 
    public AgregarDisco() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel19 = new javax.swing.JLabel();
        tbNombreD = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        tbCantanteD = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        tbAnnoD = new javax.swing.JTextField();
        tbGeneroD = new javax.swing.JTextField();
        btAgregarD = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btPathDPortada = new javax.swing.JButton();
        btPathD = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setText("Agregar Disco");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 35, -1, -1));

        tbNombreD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbNombreDActionPerformed(evt);
            }
        });
        getContentPane().add(tbNombreD, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 78, 110, -1));

        jLabel18.setText("Nombre");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 81, -1, -1));
        getContentPane().add(tbCantanteD, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 116, 110, -1));

        jLabel16.setText("Cantante");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 119, -1, -1));

        jLabel20.setText("Path");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, 10));

        jLabel15.setText("Año");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 157, -1, -1));

        jLabel21.setText("Path portada");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, 10));

        jLabel22.setText("Género");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 195, -1, -1));
        getContentPane().add(tbAnnoD, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 154, 110, -1));
        getContentPane().add(tbGeneroD, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 192, 110, -1));

        btAgregarD.setText("Agregar");
        btAgregarD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgregarDActionPerformed(evt);
            }
        });
        getContentPane().add(btAgregarD, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, -1, 20));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 373, -1, -1));

        btPathDPortada.setText("Abrir");
        btPathDPortada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPathDPortadaActionPerformed(evt);
            }
        });
        getContentPane().add(btPathDPortada, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 110, 20));

        btPathD.setText("Abrir");
        btPathD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPathDActionPerformed(evt);
            }
        });
        getContentPane().add(btPathD, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 110, 20));

        jLabel2.setText("Tipo de disco");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dígital", "Físico" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 110, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbNombreDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbNombreDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbNombreDActionPerformed

    private void btPathDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPathDActionPerformed
               if(jComboBox1.getSelectedIndex()==1){
                   JOptionPane.showMessageDialog(null, "El disco es físico");

        }else{
        
        f.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        f.showOpenDialog(f);
               }
        
    }//GEN-LAST:event_btPathDActionPerformed

    private void btAgregarDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgregarDActionPerformed
        String nombre = tbNombreD.getText();
        String cantante = tbCantanteD.getText();
        String anho = tbAnnoD.getText();
        String genero = tbGeneroD.getText();
        String ubicacion = "";
        String portada = "";
        
        if(nombre.equals("") || cantante.equals("") || anho.equals("") || genero.equals("")){
            JOptionPane.showMessageDialog(null, "No pueden haber campos vacíos");
        }
        else{
            try{
                int r = jComboBox1.getSelectedIndex();
                if (r==0){
                    ubicacion=f.getApproveButtonText();
                    portada=f2.getApproveButtonText();
                }
                else{
                    ubicacion=portada="físico";
                }
                int anho2 = Integer.parseInt(anho);
                
                RadioEmisora r1 = Principal.getEmisora();
                /* r1.Agregar_D(ubicacion, nombre, cantante, anho2, genero, portada);
                Principal.setEmisora(r1);
                this.dispose();*/
                ArrayList<Disco> listd = r1.getDiscos();
                boolean repetido = false;
                for(Disco d: listd){
                    if(d.getNombre().equals(nombre)){
                        repetido = true;
                    }
                }
                if(repetido == false){
                    Disco disc= new Disco(ubicacion, nombre, cantante, anho2, genero, portada);
                    JOptionPane.showMessageDialog(null, "Disco agregado correctamente");
                    AgregarCancion vAgC= new AgregarCancion();
                    vAgC.iniciar(disc);
                    this.dispose();
                }
                else{
                    JOptionPane.showMessageDialog(null, "El disco ya existe");
                }
                
                
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, "El año debe ser un numero");
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btAgregarDActionPerformed

    private void btPathDPortadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPathDPortadaActionPerformed
               if(jComboBox1.getSelectedIndex()==1){
                   JOptionPane.showMessageDialog(null, "El disco es físico");

        }else{        
        f2.showOpenDialog(null);
               }
    }//GEN-LAST:event_btPathDPortadaActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void iniciar(){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarDisco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarDisco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarDisco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarDisco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarDisco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAgregarD;
    private javax.swing.JButton btPathD;
    private javax.swing.JButton btPathDPortada;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JTextField tbAnnoD;
    private javax.swing.JTextField tbCantanteD;
    private javax.swing.JTextField tbGeneroD;
    private javax.swing.JTextField tbNombreD;
    // End of variables declaration//GEN-END:variables
}
