/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package progra1.GUI;

import java.util.Date;
import javax.swing.JOptionPane;
import progra1.logica.RadioEmisora;



/**
 *
 * @author Mau
 */
public class AgregarLocutor extends javax.swing.JFrame {

    /**
     * Creates new form AgregarLocutpr
     */
    public AgregarLocutor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel19 = new javax.swing.JLabel();
        tbID = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        tbDireccion = new javax.swing.JTextField();
        tbNombreLoc = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        tbCorreoLoc = new javax.swing.JTextField();
        tbTelLoc = new javax.swing.JTextField();
        jdFecNac = new com.toedter.calendar.JDateChooser();
        btAgregarLoc = new javax.swing.JButton();
        cbSexo = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setText("Agregar Locutor");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 35, -1, -1));

        tbID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbIDActionPerformed(evt);
            }
        });
        getContentPane().add(tbID, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 78, 110, -1));

        jLabel17.setText("fecha de Nacimiento:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 315, -1, -1));

        jLabel18.setText("ID");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 81, -1, -1));
        getContentPane().add(tbDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 230, 110, -1));
        getContentPane().add(tbNombreLoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 116, 110, -1));

        jLabel16.setText("Nombre");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 119, -1, -1));

        jLabel20.setText("Dirección:");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 233, -1, -1));

        jLabel15.setText("Correo:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 157, -1, -1));

        jLabel21.setText("Sexo");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 280, -1, -1));

        jLabel22.setText("teléfono:");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 195, -1, -1));
        getContentPane().add(tbCorreoLoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 154, 110, -1));
        getContentPane().add(tbTelLoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 192, 110, -1));
        getContentPane().add(jdFecNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 309, 138, -1));

        btAgregarLoc.setText("Agregar");
        btAgregarLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgregarLocActionPerformed(evt);
            }
        });
        getContentPane().add(btAgregarLoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, -1, -1));

        cbSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Femenino", "Indefinido" }));
        cbSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSexoActionPerformed(evt);
            }
        });
        getContentPane().add(cbSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 100, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbIDActionPerformed

    private void btAgregarLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgregarLocActionPerformed
        String id = tbID.getText();
        String Nombre= tbNombreLoc.getText();
        String correo = tbCorreoLoc.getText();
        String telefono = tbTelLoc.getText();
        String direccion = tbDireccion.getText();
        String sexo = cbSexo.getSelectedItem().toString();
        Date fecha = jdFecNac.getDate();
        
        if (id.equals("") || Nombre.equals("") || correo.equals("") || telefono.equals("") ||direccion.equals("") || sexo.equals("") || fecha.equals("") ){
            JOptionPane.showMessageDialog(null, "Debe rellenar todos los espacios");
        }
        
        else{
            try {
                int id2 = Integer.parseInt(id);
                
                   try {
                        int tel = Integer.parseInt(telefono);
                        RadioEmisora r = Principal.getEmisora();
                        r.Agregar_L(id2, Nombre, correo, tel, direccion, sexo, fecha);
                        Principal.setEmisora(r);
                        this.dispose();
                        JOptionPane.showMessageDialog(null, "Locutor agregado correctamente");
                    }

                     catch(Exception e){
                         JOptionPane.showMessageDialog(null, "Debe ingresar un numero en teléfono");

                    }

            }

            catch(Exception e){
                JOptionPane.showMessageDialog(null, "Debe ingresar un numero en ID");

             }
        }
       
    }//GEN-LAST:event_btAgregarLocActionPerformed

    private void cbSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSexoActionPerformed

    }//GEN-LAST:event_cbSexoActionPerformed

    /**
     * @param args the command line arguments
     */
    public void iniciar(){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarLocutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarLocutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarLocutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarLocutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarLocutor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAgregarLoc;
    private javax.swing.JComboBox cbSexo;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private com.toedter.calendar.JDateChooser jdFecNac;
    private javax.swing.JTextField tbCorreoLoc;
    private javax.swing.JTextField tbDireccion;
    private javax.swing.JTextField tbID;
    private javax.swing.JTextField tbNombreLoc;
    private javax.swing.JTextField tbTelLoc;
    // End of variables declaration//GEN-END:variables
}
