/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package progra1.GUI;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import progra1.logica.Cancion;
import progra1.logica.Disco;
import progra1.logica.RadioEmisora;
import progra1.logica.Sencillo;

/**
 *
 * @author Mau
 */
public class ConsultaGenero extends javax.swing.JFrame {

    /**
     * Creates new form ConsultaGenero
     */
    public ConsultaGenero() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tbConsultaGenero = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableGenero = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        buscarGen = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Buscar canciones por genero");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        jLabel2.setText("Género");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));
        getContentPane().add(tbConsultaGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 120, -1));

        tableGenero.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Cantante", "Album"
            }
        ));
        jScrollPane1.setViewportView(tableGenero);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 590, 300));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, -1, -1));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, -1, -1));

        buscarGen.setText("Buscar");
        buscarGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarGenActionPerformed(evt);
            }
        });
        getContentPane().add(buscarGen, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, -1, -1));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 520, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarGenActionPerformed
        
        RadioEmisora r = Principal.getEmisora();
        ArrayList<Disco> listDis = r.getDiscos();
        ArrayList<Sencillo> listSen = r.getSencillos();
        
        String genero = tbConsultaGenero.getText();
        
        DefaultTableModel model = (DefaultTableModel) tableGenero.getModel();
        model.setRowCount(0);
  
        for(Disco d : listDis){
  
            
            ArrayList<Cancion> listC = d.getCanciones();
            for(Cancion c : listC){
   
                if(c.getGenero().equals(genero)){
   
                    model.addRow(new Object[]{c.getNombre(), c.getCantante(), d.getNombre()});
                }
            }
        }
        
        for(Sencillo s : listSen){
            if(s.getGenero().equals(genero)){
                model.addRow(new Object[]{s.getNombre(), s.getCantante(), s.getAlbum()});
            }
        }
    }//GEN-LAST:event_buscarGenActionPerformed

    /**
     * @param args the command line arguments
     */
    public void iniciar(){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaGenero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaGenero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaGenero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaGenero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaGenero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarGen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableGenero;
    private javax.swing.JTextField tbConsultaGenero;
    // End of variables declaration//GEN-END:variables
}
