/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package progra1.GUI;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import progra1.logica.Cancion;
import progra1.logica.Disco;
import progra1.logica.RadioEmisora;
import progra1.logica.Sencillo;

/**
 *
 * @author Mau
 */
public class ConsultaCantante extends javax.swing.JFrame {

    /**
     * Creates new form ConsultaCantante
     */
    public ConsultaCantante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tbConsultaCantante = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCantante = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        buscarCant = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Buscar canciones por cantante");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));

        jLabel2.setText("Cantante");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));
        getContentPane().add(tbConsultaCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 120, -1));

        tableCantante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Genero", "Album"
            }
        ));
        jScrollPane1.setViewportView(tableCantante);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 660, 320));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 356, -1, -1));

        buscarCant.setText("Buscar");
        buscarCant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarCantActionPerformed(evt);
            }
        });
        getContentPane().add(buscarCant, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, -1, -1));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 500, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarCantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarCantActionPerformed
        RadioEmisora r = Principal.getEmisora();
        ArrayList<Disco> listDis = r.getDiscos();
        ArrayList<Sencillo> listSen = r.getSencillos();
        
        String cantante = tbConsultaCantante.getText();
        
        
        DefaultTableModel model = (DefaultTableModel) tableCantante.getModel();
        model.setRowCount(0);
        
        for(Disco d : listDis){
            ArrayList<Cancion> listC = d.getCanciones();
            for(Cancion c : listC){
                if(c.getCantante().equals(cantante)){
                    model.addRow(new Object[]{c.getNombre(), c.getGenero(), d.getNombre()});
                }
            }
        }
        
        for(Sencillo s : listSen){
            if(s.getCantante().equals(cantante)){
                model.addRow(new Object[]{s.getNombre(), s.getGenero(), s.getAlbum()});
            }
        }
    }//GEN-LAST:event_buscarCantActionPerformed

    /**
     * @param args the command line arguments
     */
    public void iniciar(){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaCantante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaCantante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaCantante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaCantante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaCantante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarCant;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableCantante;
    private javax.swing.JTextField tbConsultaCantante;
    // End of variables declaration//GEN-END:variables
}
