/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package progra1.GUI;

import javax.swing.JOptionPane;
import progra1.logica.RadioEmisora;

/**
 *
 * @author Mau
 */
public class CrearEmisora extends javax.swing.JFrame {

    /**
     * Creates new form CrearEmisora
     */
    
    
    
    public CrearEmisora() {
        initComponents();
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel19 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tbDirEm = new javax.swing.JTextField();
        tbNombreEm = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        tbSitioWeb = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        tbFrecuencia = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setText("Agregar Emisora");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        jLabel17.setText("Sitio web");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));
        getContentPane().add(tbDirEm, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 110, -1));

        tbNombreEm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbNombreEmActionPerformed(evt);
            }
        });
        getContentPane().add(tbNombreEm, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 110, -1));

        jLabel16.setText("Nombre");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        jLabel20.setText("Dirección:");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        jLabel21.setText("Frecuencia");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        tbSitioWeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbSitioWebActionPerformed(evt);
            }
        });
        getContentPane().add(tbSitioWeb, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 110, -1));

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, -1, -1));

        tbFrecuencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbFrecuenciaActionPerformed(evt);
            }
        });
        getContentPane().add(tbFrecuencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 110, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, -1, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 294, 40, 10));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbSitioWebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbSitioWebActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbSitioWebActionPerformed

    private void tbFrecuenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbFrecuenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbFrecuenciaActionPerformed

    private void tbNombreEmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbNombreEmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbNombreEmActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nombre = tbNombreEm.getText();
        String direccion = tbDirEm.getText();
        String frecuencia = tbFrecuencia.getText();
        String sitio = tbSitioWeb.getText();
        
        
        if (nombre.equals("") || direccion.equals("") || frecuencia.equals("") || sitio.equals("")){
            JOptionPane.showMessageDialog(null, "Debe rellenar todos los espacios");
        }
        else{
            try{
                float freq = Float.parseFloat(frecuencia);
                RadioEmisora nueva = new RadioEmisora(nombre,direccion,freq,sitio);
                Principal.setEmisora(nueva);
                this.dispose();
                JOptionPane.showMessageDialog(null, "Emisora creada correctamente");
                
                
                
                
            }
            catch(Exception e){
                
                JOptionPane.showMessageDialog(null, "La frecuencia debe ser un número decimal. Ej: 99.5");
                
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
  //  public static void main(String args[]) {
    public void iniciar(){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearEmisora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearEmisora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearEmisora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearEmisora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
      
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearEmisora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JTextField tbDirEm;
    private javax.swing.JTextField tbFrecuencia;
    private javax.swing.JTextField tbNombreEm;
    private javax.swing.JTextField tbSitioWeb;
    // End of variables declaration//GEN-END:variables
}
