/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package progra1.GUI;

import javax.swing.JOptionPane;

/**
 *
 * @author Mau
 */
public class ModificarEmisora extends javax.swing.JFrame {

    /**
     * Creates new form ModificarEmisora
     */
    public ModificarEmisora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel19 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tbDirEm = new javax.swing.JTextField();
        tbNombreEm = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        tbSitioWeb = new javax.swing.JTextField();
        tbFrecuencia = new javax.swing.JTextField();
        btModificarEm = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        tbBuscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setText("Modificar Emisora");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        jLabel17.setText("Sitio web");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));
        getContentPane().add(tbDirEm, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 110, -1));

        tbNombreEm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbNombreEmActionPerformed(evt);
            }
        });
        getContentPane().add(tbNombreEm, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 110, -1));

        jLabel16.setText("Nombre");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        jLabel20.setText("Dirección:");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        jLabel21.setText("Frecuencia");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        tbSitioWeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbSitioWebActionPerformed(evt);
            }
        });
        getContentPane().add(tbSitioWeb, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 110, -1));

        tbFrecuencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbFrecuenciaActionPerformed(evt);
            }
        });
        getContentPane().add(tbFrecuencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 110, -1));

        btModificarEm.setText("Modificar");
        btModificarEm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btModificarEmActionPerformed(evt);
            }
        });
        getContentPane().add(btModificarEm, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, -1, -1));

        jLabel1.setText("Ingrese el nombre a buscar");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 110, -1));

        tbBuscar.setText("Buscar");
        tbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(tbBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, -1, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbNombreEmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbNombreEmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbNombreEmActionPerformed

    private void tbSitioWebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbSitioWebActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbSitioWebActionPerformed

    private void tbFrecuenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbFrecuenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbFrecuenciaActionPerformed

    private void btModificarEmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btModificarEmActionPerformed
        String nombre = tbNombreEm.getText();
        String dirrecion = tbDirEm.getText();
        String frecuencia = tbFrecuencia.getText();
        String sitio = tbFrecuencia.getText();
        
        if(nombre.equals("") || dirrecion.equals("") || frecuencia.equals("") || sitio.equals("")){
            JOptionPane.showMessageDialog(null, "No pueden quedar campos vacios");
        }
        else{
            try{
                float freq = Float.parseFloat(frecuencia);
                //Modificar
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, "La frecuencia debe ser un numero decimal");
            }
            
        }
    }//GEN-LAST:event_btModificarEmActionPerformed

    private void tbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbBuscarActionPerformed
        
    }//GEN-LAST:event_tbBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public void iniciar(){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarEmisora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarEmisora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarEmisora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarEmisora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarEmisora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btModificarEm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton tbBuscar;
    private javax.swing.JTextField tbDirEm;
    private javax.swing.JTextField tbFrecuencia;
    private javax.swing.JTextField tbNombreEm;
    private javax.swing.JTextField tbSitioWeb;
    // End of variables declaration//GEN-END:variables
}
