/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package progra1.GUI;

/**
 *
 * @author Mau
 */
public class ModificarPrograma extends javax.swing.JFrame {

    /**
     * Creates new form ModificarPrograma
     */
    public ModificarPrograma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel19 = new javax.swing.JLabel();
        tbGeneroPr = new javax.swing.JTextField();
        tbNombrePr = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        Duración = new javax.swing.JLabel();
        tbHorarioPr = new javax.swing.JTextField();
        tbDuracionPr = new javax.swing.JTextField();
        cbLocutorPr = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        btBorrarPg = new javax.swing.JButton();
        btModificarPr = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tbB = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        buscarName = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setText("Modificar programa");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 35, -1, -1));
        getContentPane().add(tbGeneroPr, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 110, -1));
        getContentPane().add(tbNombrePr, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 110, -1));

        jLabel16.setText("Nombre");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        jLabel20.setText("Género:");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        jLabel15.setText("Horario");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        jLabel21.setText("Locutor");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));

        Duración.setText("Duración");
        getContentPane().add(Duración, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));
        getContentPane().add(tbHorarioPr, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 110, -1));
        getContentPane().add(tbDuracionPr, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 110, -1));

        cbLocutorPr.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cbLocutorPr, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 110, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 342, -1, -1));

        btBorrarPg.setText("Borrar");
        getContentPane().add(btBorrarPg, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, -1));

        btModificarPr.setText("Modificar");
        getContentPane().add(btModificarPr, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, -1, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, -1, -1));

        tbB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbBActionPerformed(evt);
            }
        });
        getContentPane().add(tbB, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 110, -1));

        jLabel3.setText("Nombre a encontrar");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        buscarName.setText("Buscar");
        getContentPane().add(buscarName, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbBActionPerformed

    /**
     * @param args the command line arguments
     */
    public void iniciar(){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarPrograma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarPrograma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarPrograma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarPrograma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarPrograma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Duración;
    private javax.swing.JButton btBorrarPg;
    private javax.swing.JButton btModificarPr;
    private javax.swing.JButton buscarName;
    private javax.swing.JComboBox cbLocutorPr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField tbB;
    private javax.swing.JTextField tbDuracionPr;
    private javax.swing.JTextField tbGeneroPr;
    private javax.swing.JTextField tbHorarioPr;
    private javax.swing.JTextField tbNombrePr;
    // End of variables declaration//GEN-END:variables
}
