/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package progra1.GUI;

import java.util.Date;
import javax.swing.JOptionPane;
import progra1.logica.Locutor;
import progra1.logica.RadioEmisora;

/**
 *
 * @author Mau
 */
public class ModificarLoc extends javax.swing.JFrame {

    /**
     * Creates new form ModificarLoc
     */
    
    Locutor l;
    
    public ModificarLoc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel19 = new javax.swing.JLabel();
        tbB = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        tbDireccion = new javax.swing.JTextField();
        tbNombreLoc = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        tbCorreoLoc = new javax.swing.JTextField();
        tbTelLoc = new javax.swing.JTextField();
        jdFecNac = new com.toedter.calendar.JDateChooser();
        btBorrarLoc = new javax.swing.JButton();
        btModificarLoc = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tbID1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        buscarID = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setText("Modificar locutor");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 35, -1, -1));

        tbB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbBActionPerformed(evt);
            }
        });
        getContentPane().add(tbB, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 110, -1));

        jLabel17.setText("fecha de Nacimiento:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        jLabel18.setText("ID");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));
        getContentPane().add(tbDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 110, -1));
        getContentPane().add(tbNombreLoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 110, -1));

        jLabel16.setText("Nombre");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        jLabel20.setText("Dirección:");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        jLabel15.setText("Correo:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        jLabel22.setText("teléfono:");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));
        getContentPane().add(tbCorreoLoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 110, -1));
        getContentPane().add(tbTelLoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 110, -1));
        getContentPane().add(jdFecNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 138, -1));

        btBorrarLoc.setText("Borrar");
        btBorrarLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBorrarLocActionPerformed(evt);
            }
        });
        getContentPane().add(btBorrarLoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, -1, -1));

        btModificarLoc.setText("Modificar");
        btModificarLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btModificarLocActionPerformed(evt);
            }
        });
        getContentPane().add(btModificarLoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, -1, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 470, -1, -1));

        tbID1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbID1ActionPerformed(evt);
            }
        });
        getContentPane().add(tbID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 110, -1));

        jLabel2.setText("ID del locutor a encontrar");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        buscarID.setText("Buscar");
        buscarID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarIDActionPerformed(evt);
            }
        });
        getContentPane().add(buscarID, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbBActionPerformed

    private void btBorrarLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBorrarLocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btBorrarLocActionPerformed

    private void btModificarLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btModificarLocActionPerformed
        String id = tbB.getText();
        String nuevoid = tbID1.getText();
        String nombre = tbNombreLoc.getText();
        String correo = tbCorreoLoc.getText();
        String telefono = tbTelLoc.getText();
        String direccion = tbDireccion.getText();
        String sexo="  ";
        Date fecha = jdFecNac.getDate();
        
        if(nombre.equals("") || correo.equals("") || telefono.equals("") || direccion.equals("") || sexo.equals("") || fecha.equals("") || nuevoid.isEmpty()){
            JOptionPane.showMessageDialog(null, "No pueden quedar espacios en blanco");
        }else{
            
            
        }
    }//GEN-LAST:event_btModificarLocActionPerformed

    private void tbID1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbID1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbID1ActionPerformed

    private void buscarIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarIDActionPerformed
        String id = tbB.getText();
        if(id.isEmpty()){
            JOptionPane.showMessageDialog(null, "Debe ingresar un parametro de busqueda");
        }
        else{
            RadioEmisora r = Principal.getEmisora();
            try{
                int nuevoid2 = Integer.parseInt(id);
                this.l = r.Buscar_L(nuevoid2);
                if(l==null){
                    JOptionPane.showMessageDialog(null, "No existe tal locutor");
                }
                else{
                    
                    tbID1.setText(String.valueOf(l.getIdentificador()));
                    tbNombreLoc.setText(l.getNombre());
                    tbCorreoLoc.setText(l.getCorreo());
                    tbTelLoc.setText(String.valueOf(l.getTelefono()));
                    tbDireccion.setText(l.getDireccion());
                    
                    String nuevoid = tbID1.getText();
                    String nombre = tbNombreLoc.getText();
                    String correo = tbCorreoLoc.getText();
                    String telefono = tbTelLoc.getText();
                    String direccion = tbDireccion.getText();
                    
                    Date fecha = jdFecNac.getDate();
                    
                    r.Modificar_L(nuevoid2, nuevoid2, nombre, correo, Integer.parseInt(telefono), direccion, l.getSexo(), fecha);
                    
                    Principal.setEmisora(r);
                    
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "El ID a buscar debe ser un numero valido");
            }
        }
       
    }//GEN-LAST:event_buscarIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public void iniciar(){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarLoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarLoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarLoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarLoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarLoc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBorrarLoc;
    private javax.swing.JButton btModificarLoc;
    private javax.swing.JButton buscarID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private com.toedter.calendar.JDateChooser jdFecNac;
    private javax.swing.JTextField tbB;
    private javax.swing.JTextField tbCorreoLoc;
    private javax.swing.JTextField tbDireccion;
    private javax.swing.JTextField tbID1;
    private javax.swing.JTextField tbNombreLoc;
    private javax.swing.JTextField tbTelLoc;
    // End of variables declaration//GEN-END:variables
}
