/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package progra1.GUI;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import progra1.logica.*;


/**
 *
 * @author Mau
 */
public class Principal extends javax.swing.JFrame {
    
    private static RadioEmisora emisora = null;
    

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    public static void setEmisora(RadioEmisora e) {
        emisora = e;
    }
    
     public static RadioEmisora getEmisora() {
        return emisora;
    }
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jLabel3 = new javax.swing.JLabel();
        jlmage = new javax.swing.JLabel();
        jlCancion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePlay = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btPlay = new javax.swing.JButton();
        jbStop = new javax.swing.JButton();
        cbPlay = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmCrearEm = new javax.swing.JMenuItem();
        jmCrearLoc = new javax.swing.JMenuItem();
        jmCrearPro = new javax.swing.JMenuItem();
        jmCrearAl = new javax.swing.JMenuItem();
        jmCrearC = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmModificarEm = new javax.swing.JMenuItem();
        jmModificarLoc = new javax.swing.JMenuItem();
        jmModificarPro = new javax.swing.JMenuItem();
        jmModificarD = new javax.swing.JMenuItem();
        jmModificarC = new javax.swing.JMenuItem();
        jmModificarCS = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmConsultaG = new javax.swing.JMenuItem();
        jmConsultaC = new javax.swing.JMenuItem();
        jmConsultaLoc = new javax.swing.JMenuItem();
        jmConsultaPr = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jmPlay = new javax.swing.JMenuItem();
        VaciadoCanciones = new javax.swing.JMenuItem();

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/progra1/ico/descarga.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 533));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlmage.setForeground(new java.awt.Color(255, 255, 255));
        jlmage.setText("no image");
        getContentPane().add(jlmage, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 23, 96, 78));

        jlCancion.setForeground(new java.awt.Color(255, 255, 255));
        jlCancion.setText("Canción");
        getContentPane().add(jlCancion, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 55, -1, -1));

        tablePlay.setBackground(new java.awt.Color(153, 0, 0));
        tablePlay.setForeground(new java.awt.Color(255, 255, 255));
        tablePlay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Canción", "Artista", "Álbum", "Género"
            }
        ));
        jScrollPane1.setViewportView(tablePlay);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 500, 110));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 480, -1, -1));

        btPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/progra1/ico/button_blue_play.png"))); // NOI18N
        getContentPane().add(btPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 70, 60));

        jbStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/progra1/ico/stop.png"))); // NOI18N
        jbStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbStopActionPerformed(evt);
            }
        });
        getContentPane().add(jbStop, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 80, 60));

        cbPlay.setBackground(new java.awt.Color(0, 0, 0));
        cbPlay.setForeground(new java.awt.Color(255, 255, 255));
        cbPlay.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecccionar Programa" }));
        cbPlay.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                cbPlayPopupMenuWillBecomeVisible(evt);
            }
        });
        cbPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPlayActionPerformed(evt);
            }
        });
        getContentPane().add(cbPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/progra1/ico/descarga.jpg"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jMenu1.setText("Agregar");

        jmCrearEm.setText("Crear Emisora");
        jmCrearEm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCrearEmActionPerformed(evt);
            }
        });
        jMenu1.add(jmCrearEm);

        jmCrearLoc.setText("Registrar locutor");
        jmCrearLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCrearLocActionPerformed(evt);
            }
        });
        jMenu1.add(jmCrearLoc);

        jmCrearPro.setText("Registrar programa");
        jmCrearPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCrearProActionPerformed(evt);
            }
        });
        jMenu1.add(jmCrearPro);

        jmCrearAl.setText("Registrar Album");
        jmCrearAl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCrearAlActionPerformed(evt);
            }
        });
        jMenu1.add(jmCrearAl);

        jmCrearC.setText("Registrar canción suelta");
        jmCrearC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCrearCActionPerformed(evt);
            }
        });
        jMenu1.add(jmCrearC);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Modificar");

        jmModificarEm.setText("Modificar emisora");
        jmModificarEm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmModificarEmActionPerformed(evt);
            }
        });
        jMenu2.add(jmModificarEm);

        jmModificarLoc.setText("Modificar Locutor");
        jmModificarLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmModificarLocActionPerformed(evt);
            }
        });
        jMenu2.add(jmModificarLoc);

        jmModificarPro.setText("Modificar programa");
        jmModificarPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmModificarProActionPerformed(evt);
            }
        });
        jMenu2.add(jmModificarPro);

        jmModificarD.setText("Modificar disco");
        jmModificarD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmModificarDActionPerformed(evt);
            }
        });
        jMenu2.add(jmModificarD);

        jmModificarC.setText("Modificar canción");
        jmModificarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmModificarCActionPerformed(evt);
            }
        });
        jMenu2.add(jmModificarC);

        jmModificarCS.setText("Modificar canción suelta");
        jmModificarCS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmModificarCSActionPerformed(evt);
            }
        });
        jMenu2.add(jmModificarCS);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Consultas");

        jmConsultaG.setText("Canciones por género");
        jmConsultaG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmConsultaGActionPerformed(evt);
            }
        });
        jMenu3.add(jmConsultaG);

        jmConsultaC.setText("Canciones por cantante");
        jmConsultaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmConsultaCActionPerformed(evt);
            }
        });
        jMenu3.add(jmConsultaC);

        jmConsultaLoc.setText("Locutores");
        jmConsultaLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmConsultaLocActionPerformed(evt);
            }
        });
        jMenu3.add(jmConsultaLoc);

        jmConsultaPr.setText("Programas");
        jmConsultaPr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmConsultaPrActionPerformed(evt);
            }
        });
        jMenu3.add(jmConsultaPr);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Playlist");

        jmPlay.setText("Crear playlist");
        jmPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmPlayActionPerformed(evt);
            }
        });
        jMenu4.add(jmPlay);

        VaciadoCanciones.setText("Vaciado de canciones");
        VaciadoCanciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VaciadoCancionesActionPerformed(evt);
            }
        });
        jMenu4.add(VaciadoCanciones);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmCrearEmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCrearEmActionPerformed

        // TODO add your handling code here:
        if (emisora==null){
             CrearEmisora vCrearEm=new CrearEmisora();
            vCrearEm.iniciar();
        }
        else{
            JOptionPane.showMessageDialog(null, "Ya existe una emisora");
        }
    }//GEN-LAST:event_jmCrearEmActionPerformed

    private void jmCrearLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCrearLocActionPerformed
        
        if (emisora!=null){
        AgregarLocutor vAgregarLo=new AgregarLocutor();
        vAgregarLo.iniciar();  
           
       }
       
       else{
           JOptionPane.showMessageDialog(null, "Debe crear emisora primero");
          
           
           
       }        
        
             // TODO add your handling code here:
    }//GEN-LAST:event_jmCrearLocActionPerformed

    private void jmModificarCSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmModificarCSActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jmModificarCSActionPerformed

    private void jmModificarDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmModificarDActionPerformed
        
    }//GEN-LAST:event_jmModificarDActionPerformed

    private void jmConsultaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmConsultaCActionPerformed
        ConsultaCantante v1= new ConsultaCantante ();
        v1.iniciar();
    }//GEN-LAST:event_jmConsultaCActionPerformed

    private void jmConsultaLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmConsultaLocActionPerformed
         ConsultaLocutores vConsloc = new ConsultaLocutores();
        vConsloc.iniciar();
    }//GEN-LAST:event_jmConsultaLocActionPerformed

    private void jmPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmPlayActionPerformed
        SeleccionarPrograma vSelPro=new SeleccionarPrograma();
        vSelPro.iniciar();         
    }//GEN-LAST:event_jmPlayActionPerformed

    private void jbStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbStopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbStopActionPerformed

    private void jmCrearProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCrearProActionPerformed
        if(emisora!=null){
            if(!emisora.getLocutores().isEmpty()){
                AgregarPrograma vAgregarPro=new AgregarPrograma();
                 vAgregarPro.iniciar();
            }
            else{
                
                JOptionPane.showMessageDialog(null, "Debe crear locutor primero");
            }
        } 
        
        else{
           JOptionPane.showMessageDialog(null, "Debe crear emisora primero");
        }

    }//GEN-LAST:event_jmCrearProActionPerformed

    private void jmCrearAlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCrearAlActionPerformed
        if (emisora!=null){
        AgregarDisco vAgregarD=new AgregarDisco();
        vAgregarD.iniciar(); 
           
       }
       
       else{
           JOptionPane.showMessageDialog(null, "Debe crear emisora primero");
          
           
           
       }  
        // TODO add your handling code here:
    }//GEN-LAST:event_jmCrearAlActionPerformed

    private void jmCrearCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCrearCActionPerformed
                if (emisora!=null){
        AgregarCancionSuelta vAgregarCS=new AgregarCancionSuelta();
        
        vAgregarCS.iniciar();  
           
       }
       
       else{
           JOptionPane.showMessageDialog(null, "Debe crear emisora primero");
          
           
           
       }  
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jmCrearCActionPerformed

    private void jmModificarEmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmModificarEmActionPerformed
       
    }//GEN-LAST:event_jmModificarEmActionPerformed

    private void jmModificarLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmModificarLocActionPerformed
        
    }//GEN-LAST:event_jmModificarLocActionPerformed

    private void jmModificarProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmModificarProActionPerformed
        // TODO add your handling code here
        ModificarPrograma vModPro=new ModificarPrograma();
        vModPro.iniciar();   
    }//GEN-LAST:event_jmModificarProActionPerformed

    private void jmModificarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmModificarCActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jmModificarCActionPerformed

    private void VaciadoCancionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VaciadoCancionesActionPerformed
            JFileChooser f = new JFileChooser();
            f.showSaveDialog(f);
            String p= f.getSelectedFile().getAbsolutePath();
            try{
                 emisora.escribirExel_Albunes(p);
            } catch (Exception e){
                JOptionPane.showMessageDialog(null, "No se pudo guardar");
                
            }
            
    }//GEN-LAST:event_VaciadoCancionesActionPerformed

    private void jmConsultaGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmConsultaGActionPerformed
       if(emisora == null){
            JOptionPane.showMessageDialog(null, "Debe crear emisora primero");
        }
        else{
            ConsultaGenero vCG = new ConsultaGenero();
            vCG.iniciar();
        }
    }//GEN-LAST:event_jmConsultaGActionPerformed

    private void jmConsultaPrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmConsultaPrActionPerformed
        ConsultaProgramas v3 =new ConsultaProgramas();
        v3.iniciar();
    }//GEN-LAST:event_jmConsultaPrActionPerformed

    private void cbPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPlayActionPerformed

        if (cbPlay.getSelectedIndex() !=0){
        
        String NombreP = cbPlay.getSelectedItem().toString();
        ArrayList<Programa> listP = emisora.getProgramas();
        DefaultTableModel model = (DefaultTableModel) tablePlay.getModel();
        model.setRowCount(0);
        for(Programa p: listP){
            ArrayList listC = p.getPlaylist();
            if(listC.isEmpty()){
                JOptionPane.showMessageDialog(null, "Este programa no tiene ningún playlist");
            }
            else{
                for(int i=0; i<listC.size(); i++){
                    if(listC.get(i) instanceof Cancion){
                        Cancion c = (Cancion)listC.get(i);
                        model.addRow(new Object[]{c.getNombre(), c.getCantante(), c.getDisco(), c.getGenero()});
                    }
                    if(listC.get(i) instanceof Sencillo){
                        Sencillo s = (Sencillo)listC.get(i);
                        model.addRow(new Object[]{s.getNombre(), s.getCantante(), s.getAlbum(), s.getGenero()});
                    }
                }
            }
        }
        }else{}
        
            
        
    }//GEN-LAST:event_cbPlayActionPerformed

    private void cbPlayPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbPlayPopupMenuWillBecomeVisible
              /*  if (emisora.getProgramas().isEmpty()==true){
                    
           
        }else{
            
            ArrayList<Programa> listP = emisora.getProgramas();
            for(Programa p : listP){
                cbPlay.addItem(p.getNombre());    
            }   
        }*/
        
        try{
            if (cbPlay.getItemCount()>1){
            cbPlay.removeAllItems();
            cbPlay.addItem("Seleccionar Playlist");
            ArrayList<Programa> listP = emisora.getProgramas();
            for(Programa p : listP){
            cbPlay.addItem(p.getNombre()); 
            }
            
            
            
            
            }else{}
        }
        catch(Exception e){
                System.out.println("");
        }
    }//GEN-LAST:event_cbPlayPopupMenuWillBecomeVisible
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem VaciadoCanciones;
    private javax.swing.JButton btPlay;
    private javax.swing.JComboBox cbPlay;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbStop;
    private javax.swing.JLabel jlCancion;
    private javax.swing.JLabel jlmage;
    private javax.swing.JMenuItem jmConsultaC;
    private javax.swing.JMenuItem jmConsultaG;
    private javax.swing.JMenuItem jmConsultaLoc;
    private javax.swing.JMenuItem jmConsultaPr;
    private javax.swing.JMenuItem jmCrearAl;
    private javax.swing.JMenuItem jmCrearC;
    private javax.swing.JMenuItem jmCrearEm;
    private javax.swing.JMenuItem jmCrearLoc;
    private javax.swing.JMenuItem jmCrearPro;
    private javax.swing.JMenuItem jmModificarC;
    private javax.swing.JMenuItem jmModificarCS;
    private javax.swing.JMenuItem jmModificarD;
    private javax.swing.JMenuItem jmModificarEm;
    private javax.swing.JMenuItem jmModificarLoc;
    private javax.swing.JMenuItem jmModificarPro;
    private javax.swing.JMenuItem jmPlay;
    private javax.swing.JTable tablePlay;
    // End of variables declaration//GEN-END:variables
}
